<a href="https://colab.research.google.com/github/9465565598/ThaparWorkshopANN/blob/master/skikit_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#SVM CLASSIFIER

In [0]:
import numpy as np
import sklearn
from sklearn import svm
from sklearn import datasets

sklearn.__version__

'0.21.2'

In [0]:
iris = datasets.load_iris()

In [0]:
type(iris)

sklearn.utils.Bunch

In [0]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [0]:
iris.feature_names


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [0]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [0]:
iris.target_names


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [0]:
x = iris.data[:,2]
y = iris.target

In [0]:
from sklearn.model_selection import train_test_split


In [0]:
#X-train,X_test,y_train,y_test=cross_validation.train_test_split(x,y,test_size=0.2,random_state=4)
from sklearn.model_selection import cross_validate


x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=4)
y_train.T

array([1, 0, 2, 0, 1, 2, 2, 1, 1, 0, 2, 0, 1, 0, 2, 0, 0, 1, 1, 2, 0, 1,
       2, 2, 1, 1, 0, 1, 2, 1, 0, 1, 0, 1, 2, 1, 2, 1, 0, 2, 2, 0, 1, 2,
       0, 2, 1, 2, 1, 0, 2, 1, 2, 0, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1, 2, 1,
       1, 0, 2, 0, 1, 0, 1, 1, 1, 1, 0, 2, 2, 1, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 2, 0, 0, 2, 2, 1, 0, 0, 0, 2, 1, 0, 0, 2, 1, 2, 0, 0, 2, 1, 1,
       1, 2, 2, 1, 2, 1, 1, 2, 2, 2])

In [0]:
x_train_mod = x_train.reshape(-1,1)
x_test_mod = x_test.reshape(-1,1)
y_train_mod = y_train.reshape(-1,1)
y_test_mod = y_test.reshape(-1,1)

y_train_mod

array([[1],
       [0],
       [2],
       [0],
       [1],
       [2],
       [2],
       [1],
       [1],
       [0],
       [2],
       [0],
       [1],
       [0],
       [2],
       [0],
       [0],
       [1],
       [1],
       [2],
       [0],
       [1],
       [2],
       [2],
       [1],
       [1],
       [0],
       [1],
       [2],
       [1],
       [0],
       [1],
       [0],
       [1],
       [2],
       [1],
       [2],
       [1],
       [0],
       [2],
       [2],
       [0],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [1],
       [0],
       [2],
       [1],
       [2],
       [0],
       [2],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [0],
       [2],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [1],
       [1],
       [1],
       [0],
    

In [0]:
model=svm.SVC(kernel='linear')


In [0]:
model.fit(x_train_mod,y_train_mod)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [0]:
accuracy = model.score(x_test_mod,y_test_mod)
accuracy

0.9666666666666667